default_ttl: 300

records:
  - name: example.com.
    type: A
    value: 203.0.113.10

  - name: example.com.
    type: AAAA
    value: 2001:db8::10

  - name: www.example.com.
    type: CNAME
    value: example.com.

  - name: example.com.
    type: NS
    value: ns1.example.com.

  - name: example.com.
    type: TXT
    value: "v=spf1 -all"

  - name: 10.113.0.203.in-addr.arpa.
    type: PTR
    value: example.com.

  - name: mail.example.com.
    type: A
    value: 203.0.113.20

  - name: ns1.example.com.
    type: A
    value: 203.0.113.30
